apiVersion: v1
kind: Secret
metadata:
  name: cpi-global-secret
  namespace: kube-system
stringData:
  <yourVcenterIP>.username: "administrator@vsphere.local"
  <yourVcenterIP>.password: "<yourPassword>"
